# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_remove_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default=b''),
        ),
    ]
